---
title: "progress-report-wolfc910.Rmd"
author: "Carter Wolf"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, cache=TRUE}
library(Lahman)
library(ggplot2)
library(dplyr)
library(rvest)
library(readr)

url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)
write.csv(tables[[1]], "temp.csv", row.names=FALSE)
backin <- readr::read_csv("temp.csv", skip = 1, show_col_types =FALSE)

colnames(backin)[2] <- "playerID"
colnames(backin)[4] <- "votes"
backin$yearID <- c(2023)
backin$needed <- c(292)
backin$inducted <- c('Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N')
backup <- select(backin, 2,40,4,41,42)

HOF <- select(HallOfFame, 1,2,6,5,7)

total <- rbind(backup, HOF)
total

total %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2023))
```
